import type { TranslationDict } from './catalogues';

export const en: TranslationDict = {
  'app.name': 'FoxPlan',
  'app.tagline': 'Plan your trips on a single map.',

  'nav.trips': 'Trips',
  'nav.map': 'Map',
  'nav.itinerary': 'Itinerary',
  'nav.places': 'Places',
  'nav.accommodation': 'Stays',
  'nav.settings': 'Settings',
  'nav.data': 'Data',

  'trips.title': 'My trips',
  'trips.new': 'New trip',
  'trips.empty': 'No trips yet. Create one to get started.',
  'trips.namePlaceholder': 'Trip name',
  'trips.destinationPlaceholder': 'Destination (city, region…)',
  'trips.create': 'Create',
  'trips.rename': 'Rename',
  'trips.duplicate': 'Duplicate',
  'trips.delete': 'Delete',
  'trips.deleteConfirm': 'Delete this trip and all its local data?',
  'trips.active': 'Active trip',
  'trips.select': 'Open',
  'trips.dates': 'Dates',
  'trips.startDate': 'Start',
  'trips.endDate': 'End',

  'map.title': 'Map',
  'map.searchPlaceholder': 'Search a place, restaurant, activity…',
  'map.search': 'Search',
  'map.keyMissing': 'Add your Google Maps key in settings to display the map.',
  'map.keyMissingCta': 'Open settings',
  'map.loading': 'Loading map…',
  'map.error': 'Unable to load the map. Check your key and restrictions.',
  'map.noTrip': 'Select or create a trip to display the map.',

  'filters.title': 'Filters',
  'category.restaurant': 'Restaurants',
  'category.activity': 'Activities',
  'category.attraction': 'Attractions',
  'category.airport': 'Airports',
  'category.transport': 'Transport',
  'category.lodging': 'Stays',
  'category.other': 'Other',

  'places.title': 'Places',
  'places.results': 'Results',
  'places.saved': 'Saved places',
  'places.save': 'Save',
  'places.remove': 'Remove',
  'places.noResults': 'No results. Start a search from the map.',
  'places.noSaved': 'No saved places for this trip.',
  'places.notes': 'Notes',
  'places.category': 'Category',
  'places.rating': 'Rating',
  'places.openInGoogle': 'View on Google Maps',
  'places.visitWhen': 'When?',
  'places.visitStart': 'Date',
  'places.visitEnd': 'End (optional)',

  'proximity.title': 'Proximity',
  'proximity.straightLine': 'Straight line',
  'proximity.route': 'By route',
  'proximity.compute': 'Compute route',
  'proximity.from': 'From',
  'proximity.pickReference': 'Pick a reference point (stay, airport…).',

  'routes.title': 'Itinerary',
  'routes.addStop': 'Add stop',
  'routes.noStops': 'Add at least two stops to compute a route.',
  'routes.calculate': 'Calculate',
  'routes.mode.DRIVING': 'Driving',
  'routes.mode.TRANSIT': 'Transit',
  'routes.mode.BICYCLING': 'Cycling',
  'routes.mode.WALKING': 'Walking',
  'routes.mode.TWO_WHEELER': 'Two-wheeler',
  'routes.mode.FLIGHT': 'Flight',
  'routes.total': 'Total',
  'routes.duration': 'Duration',
  'routes.distance': 'Distance',
  'routes.unavailable': 'Mode unavailable for this route.',
  'routes.moveUp': 'Move up',
  'routes.moveDown': 'Move down',
  'routes.removeStop': 'Remove stop',
  'routes.tab.route': 'Route planner',
  'routes.tab.overview': 'Trip overview',

  'overview.title': 'Trip overview',
  'overview.intro':
    'Saved places with a date are ordered chronologically. Travel time between each step is computed automatically.',
  'overview.noPlaces': 'Add a date to your saved places to build the trip timeline.',
  'overview.undated': 'Places without a date',
  'overview.flightNoRoute': 'Flight — no route drawn',
  'overview.recalculate': 'Recalculate travel',
  'overview.calculating': 'Computing travel…',
  'overview.segmentMode': 'Mode',

  'accommodation.title': 'Stays',
  'accommodation.searchTitle': 'Search a stay',
  'accommodation.destination': 'City / destination',
  'accommodation.checkIn': 'Check-in',
  'accommodation.checkOut': 'Check-out',
  'accommodation.adults': 'Adults',
  'accommodation.rooms': 'Rooms',
  'accommodation.budgetMax': 'Max budget / night',
  'accommodation.provider': 'Provider',
  'accommodation.openSearch': 'Open search',
  'accommodation.disclaimer':
    'The search opens on the provider website. Live prices and availability are shown there.',
  'accommodation.saveCandidate': 'Save an option',
  'accommodation.candidates': 'Saved options',
  'accommodation.noCandidates': 'No saved options for this trip.',
  'accommodation.name': 'Stay name',
  'accommodation.sourceUrl': 'Link (optional)',
  'accommodation.price': 'Price',
  'accommodation.remove': 'Remove',

  'settings.title': 'Settings',
  'settings.mapsKeyTitle': 'Google Maps API key',
  'settings.mapsKeyLabel': 'API key',
  'settings.mapsKeyPlaceholder': 'Paste your Google Maps key',
  'settings.mapsKeyHelp':
    'The key is stored only in this browser and is never exported. Restrict it by domain and API in Google Cloud.',
  'settings.mapsKeyWarning':
    'Google Maps usage may incur charges on your Google Cloud project.',
  'settings.saveKey': 'Save and initialize',
  'settings.replaceKey': 'Replace key',
  'settings.removeKey': 'Remove key',
  'settings.keyConfigured': 'Key configured',
  'settings.keyNotConfigured': 'No key configured',
  'settings.language': 'Language',
  'settings.theme': 'Theme',
  'settings.theme.dark': 'Dark',
  'settings.theme.light': 'Light',
  'settings.docLink': 'How to create a Google Maps key',

  'data.title': 'Local data',
  'data.notice':
    'All your data is stored in this browser. Clearing browser data may remove it.',
  'data.export': 'Export (JSON)',
  'data.import': 'Import (JSON)',
  'data.importReplace': 'Replace',
  'data.importMerge': 'Merge',
  'data.importSuccess': 'Import successful.',
  'data.importError': 'Invalid file: import cancelled.',
  'data.exportEmpty': 'No data to export.',

  'common.cancel': 'Cancel',
  'common.save': 'Save',
  'common.close': 'Close',
  'common.confirm': 'Confirm',
  'common.optional': 'optional',
  'common.loading': 'Loading…',
  'common.none': 'None',
};
