export const fr = {
  'app.name': 'FoxPlan',
  'app.tagline': 'Planifiez vos voyages sur une seule carte.',

  'nav.trips': 'Voyages',
  'nav.map': 'Carte',
  'nav.itinerary': 'Itinéraire',
  'nav.places': 'Lieux',
  'nav.accommodation': 'Hébergements',
  'nav.settings': 'Réglages',
  'nav.data': 'Données',

  'trips.title': 'Mes voyages',
  'trips.new': 'Nouveau voyage',
  'trips.empty': 'Aucun voyage pour le moment. Créez-en un pour commencer.',
  'trips.namePlaceholder': 'Nom du voyage',
  'trips.destinationPlaceholder': 'Destination (ville, région…)',
  'trips.create': 'Créer',
  'trips.rename': 'Renommer',
  'trips.duplicate': 'Dupliquer',
  'trips.delete': 'Supprimer',
  'trips.deleteConfirm': 'Supprimer ce voyage et toutes ses données locales ?',
  'trips.active': 'Voyage actif',
  'trips.select': 'Ouvrir',
  'trips.dates': 'Dates',
  'trips.startDate': 'Départ',
  'trips.endDate': 'Retour',

  'map.title': 'Carte',
  'map.searchPlaceholder': 'Rechercher un lieu, un restaurant, une activité…',
  'map.search': 'Rechercher',
  'map.keyMissing': 'Ajoutez votre clé Google Maps dans les réglages pour afficher la carte.',
  'map.keyMissingCta': 'Ouvrir les réglages',
  'map.loading': 'Chargement de la carte…',
  'map.error': 'Impossible de charger la carte. Vérifiez votre clé et vos restrictions.',
  'map.noTrip': 'Sélectionnez ou créez un voyage pour afficher la carte.',

  'filters.title': 'Filtres',
  'category.city': 'Villes',
  'category.restaurant': 'Restaurants',
  'category.activity': 'Activités',
  'category.attraction': 'Attractions',
  'category.airport': 'Aéroports',
  'category.transport': 'Transports',
  'category.lodging': 'Hébergements',
  'category.other': 'Autres',

  'places.title': 'Lieux',
  'places.results': 'Résultats',
  'places.saved': 'Lieux enregistrés',
  'places.save': 'Enregistrer',
  'places.remove': 'Retirer',
  'places.noResults': 'Aucun résultat. Lancez une recherche depuis la carte.',
  'places.noSaved': 'Aucun lieu enregistré pour ce voyage.',
  'places.notes': 'Notes',
  'places.category': 'Catégorie',
  'places.rating': 'Note',
  'places.openInGoogle': 'Voir sur Google Maps',
  'places.visitWhen': 'Quand ?',
  'places.visitStart': 'Date',
  'places.visitEnd': 'Fin (facultatif)',
  'places.edit': 'Modifier',
  'places.noDate': 'Aucune date',

  'proximity.title': 'Proximité',
  'proximity.straightLine': 'À vol d’oiseau',
  'proximity.route': 'Par itinéraire',
  'proximity.compute': 'Calculer le trajet',
  'proximity.from': 'Depuis',
  'proximity.pickReference': 'Choisissez un point de référence (hébergement, aéroport…).',

  'routes.title': 'Itinéraire',
  'routes.addStop': 'Ajouter une étape',
  'routes.noStops': 'Ajoutez au moins deux étapes pour calculer un itinéraire.',
  'routes.calculate': 'Calculer',
  'routes.mode.DRIVING': 'Voiture',
  'routes.mode.TRANSIT': 'Transports',
  'routes.mode.BICYCLING': 'Vélo',
  'routes.mode.WALKING': 'Marche',
  'routes.mode.TWO_WHEELER': 'Deux-roues',
  'routes.mode.FLIGHT': 'Avion',
  'routes.total': 'Total',
  'routes.duration': 'Durée',
  'routes.distance': 'Distance',
  'routes.unavailable': 'Mode indisponible pour ce trajet.',
  'routes.moveUp': 'Monter',
  'routes.moveDown': 'Descendre',
  'routes.removeStop': 'Retirer l’étape',
  'routes.tab.route': 'Calcul de trajet',
  'routes.tab.overview': 'Aperçu du voyage',

  'overview.title': 'Aperçu du voyage',
  'overview.intro':
    'Les lieux enregistrés avec une date sont classés chronologiquement. Le temps de trajet entre chaque étape est calculé automatiquement.',
  'overview.noPlaces':
    'Ajoutez une date à vos lieux enregistrés pour construire la chronologie du voyage.',
  'overview.undated': 'Lieux sans date',
  'overview.flightNoRoute': 'Vol — pas de tracé',
  'overview.recalculate': 'Recalculer les trajets',
  'overview.calculating': 'Calcul des trajets…',
  'overview.segmentMode': 'Mode',

  'accommodation.title': 'Hébergements',
  'accommodation.searchTitle': 'Rechercher un hébergement',
  'accommodation.destination': 'Ville / destination',
  'accommodation.checkIn': 'Arrivée',
  'accommodation.checkOut': 'Départ',
  'accommodation.adults': 'Adultes',
  'accommodation.rooms': 'Chambres',
  'accommodation.budgetMax': 'Budget max / nuit',
  'accommodation.provider': 'Fournisseur',
  'accommodation.openSearch': 'Ouvrir la recherche',
  'accommodation.disclaimer':
    'La recherche s’ouvre sur le site du fournisseur. Les prix et disponibilités y sont affichés en direct.',
  'accommodation.saveCandidate': 'Enregistrer une option',
  'accommodation.candidates': 'Options enregistrées',
  'accommodation.noCandidates': 'Aucune option enregistrée pour ce voyage.',
  'accommodation.name': 'Nom de l’hébergement',
  'accommodation.sourceUrl': 'Lien (facultatif)',
  'accommodation.price': 'Prix',
  'accommodation.remove': 'Retirer',

  'settings.title': 'Réglages',
  'settings.mapsKeyTitle': 'Clé API Google Maps',
  'settings.mapsKeyLabel': 'Clé API',
  'settings.mapsKeyPlaceholder': 'Collez votre clé Google Maps',
  'settings.mapsKeyHelp':
    'La clé est stockée uniquement dans ce navigateur et n’est jamais exportée. Restreignez-la par domaine et par API dans Google Cloud.',
  'settings.mapsKeyWarning':
    'L’utilisation de Google Maps peut engendrer des coûts sur votre projet Google Cloud.',
  'settings.saveKey': 'Enregistrer et initialiser',
  'settings.replaceKey': 'Remplacer la clé',
  'settings.removeKey': 'Supprimer la clé',
  'settings.keyConfigured': 'Clé configurée',
  'settings.keyNotConfigured': 'Aucune clé configurée',
  'settings.language': 'Langue',
  'settings.theme': 'Thème',
  'settings.theme.dark': 'Sombre',
  'settings.theme.light': 'Clair',
  'settings.docLink': 'Comment créer une clé Google Maps',

  'data.title': 'Données locales',
  'data.notice':
    'Toutes vos données sont stockées dans ce navigateur. Effacer les données du navigateur peut les supprimer.',
  'data.export': 'Exporter (JSON)',
  'data.import': 'Importer (JSON)',
  'data.scopeAll': 'Tous les voyages',
  'data.scopeActive': 'Voyage actif',
  'data.noActiveTrip': 'Aucun voyage actif à exporter.',
  'data.importChoose': 'Choisir un fichier',
  'data.importFound': '{count} voyage(s) trouvé(s) dans le fichier',
  'data.importWhich': 'Voyages à importer',
  'data.importReplace': 'Remplacer',
  'data.importMerge': 'Fusionner',
  'data.importApply': 'Importer',
  'data.importSuccess': 'Import réussi.',
  'data.importError': 'Fichier invalide : import annulé.',
  'data.exportEmpty': 'Aucune donnée à exporter.',

  'common.cancel': 'Annuler',
  'common.save': 'Enregistrer',
  'common.close': 'Fermer',
  'common.confirm': 'Confirmer',
  'common.optional': 'facultatif',
  'common.loading': 'Chargement…',
  'common.none': 'Aucun',
};
